add harvard-cs50 school
Hexlet/hexlet-comparator pull request #131
Opened 2023-01-26 11:07 UTC by ayayalice

Added school

2023-01-27 08:38 UTC, ashikov commented
@ayayalice тут билд завалился. Нужно починить

2023-01-27 08:41 UTC, ashikov requested changes

2023-01-27 08:41 UTC, ashikov commented on data/schools/harvard-cs50.yml
> +Contact: "https://courses.edx.org/support/contact_us" # адрес почты не указан
Комментарии подобного вида в коде излишни. Такие вещи можно обсудить в самой переписке в пулреквесте просто ссылаясь на строки и задавая вопросы.

2023-01-27 08:41 UTC, ashikov commented on data/schools/harvard-cs50.yml
> +foundationDate: 2015 # не точная дата
И этот коммент тоже

2023-01-27 08:41 UTC, ashikov commented on data/schools/harvard-cs50.yml
> +  exists: false # Как я понял этот пункт про академ...
Вот тут очень наглядно. Представьте себя на месте человека, который посмотрит в этот файл через год. Кто тут, что понял да и какая ему будет разница? :)

2023-01-27 11:07 UTC, ayayalice commented on data/schools/harvard-cs50.yml
> +  exists: false # Как я понял этот пункт про академ...
@ashikov Всё понял уберу и исправлю, спасибо)

2023-01-30 06:26 UTC, ashikov commented
@ayayalice сборка так и валится)

2023-02-06 10:36 UTC, ayayalice commented
@emp7yhead Да, сори, пришлось отвлечься от проекта, сегодня постараюсь починить, или завтра если что. Уже работаю над этим)

2023-02-08 18:17 UTC, ayayalice commented
@ashikov Не получается разобраться, почему падает билд, может потому что школа иностранная?
И вывод ошибки, так понимаю оно сравнивает с уже существующими школами и потом выдаёт мне ошибку.
Куда мне следует обратиться за помощью? Или как лучше поступить сейчас?

2023-02-09 06:59 UTC, ssssank commented
@ayayalice у вас повторяется ключ "links", тесты об этом говорят:
```
 YAMLException: duplicated mapping key (67:3)

 64 | mobile:
 65 |   exists: true
 66 |   links: "https://www.edx.org/cou ...
 67 |   links: "https://apps.apple.com/ ...
```

2023-02-13 10:43 UTC, merged