#137 Добавить тег rel canonical
Hexlet/hexlet-comparator pull request #150
Opened 2023-02-27 17:19 UTC by EvSedov

@fey, adds tag with canonical url on pages

[deploy](https://evsedov-comparator.onrender.com)

2023-02-27 17:28 UTC, fey commented on pages/_app.jsx
> +  const canonicalUrl = (BASE_URL + (router.asPath === '/' ? '' : router.asPath)).split('?')[0];
в глаза сразу бросается то, что в одну строку записано. Плюс наверняка есть встроенные возможности для работы с урлами. @dzencot подскажешь?
Плюс ссылки мы обычно строим не через конкатекацию.
По базовым урлам - обычно они задаются через переменные окружения. Думаю стоит поковырять, как можно задать переменные окружения для nextJS через файлик `.env` для локальной разработки.

2023-02-28 03:29 UTC, EvSedov commented on pages/_app.jsx
> +  const canonicalUrl = (BASE_URL + (router.asPath === '/' ? '' : router.asPath)).split('?')[0];
@fey Ок.
1. Пофикшу код чуть позже.
2. Если есть встроенные возможности по работе с урлами @dzencot подсказывай =), я конечно и сам поищу.
3. Базовые урлы переделаю через переменные окружения, через файл '. env.local'.
4. Вместо конкатенации строк для формирования ссылок интерполяция строк пойдет?

2023-02-28 09:50 UTC, fey commented on pages/_app.jsx
> +  const canonicalUrl = (BASE_URL + (router.asPath === '/' ? '' : router.asPath)).split('?')[0];
файлик должен называться `.env`, он создается только при разработке локально. На проде задаются переменные окружения.
Вместо конкатенации обычно используем джойн массива. Надо будет подождать ревью @dzencot

2023-02-28 14:16 UTC, fey commented on pages/_app.jsx
> +  const BASE_URL = process.env.HOST_NAME || 'http://localhost:3000';
смотри, у тебя обе константы в верхнем регистре, почему не в нижнем?
Плюс BASE_URL норм для константы окружения. Ведь мы должны передать не имя хоста (это имя домена по сути, типа hexlet.io), а именно что урл.

2023-02-28 14:26 UTC, fey commented on pages/_app.jsx
> +  const canonicalUrl = [BASE_URL, ADDITIONAL_URL].join('').split('?')[0];
URL не получится использовать? https://nodejs.org/api/url.html

2023-02-28 17:28 UTC, EvSedov commented on pages/_app.jsx
> +  const canonicalUrl = [BASE_URL, ADDITIONAL_URL].join('').split('?')[0];
@fey а как проверить, что на продакшене переменная окружения из process.env.NEXT_PUBLIC_BASE_URL подгружается как надо? А то я что-то в этом сомневаюсь.

2023-03-01 07:00 UTC, EvSedov commented on pages/_app.jsx
> +  const canonicalUrl = [BASE_URL, ADDITIONAL_URL].join('').split('?')[0];
@fey вопрос который задал выше снимается, на render.com почистил кэш и перезапустил деплой, все отработало корректно.

2023-03-01 08:05 UTC, fey commented on pages/_app.jsx
> +  const canonicalUrl = [BASE_URL, ADDITIONAL_URL].join('').split('?')[0];
Никак, подождать когда задеплоят и поставят переменную :)

2023-03-01 08:05 UTC, fey commented
@dzencot нужно задеплоить, поревьювить и задать верную переменную `https://schools.hexlet.io/`

2023-03-06 08:05 UTC, fey commented
Здесь у тебя затянулись изменения из другой ветки. Их можно удалить (они у тебя в другой ветке).
А чтобы другие изменения можно было делать, можно создать новую ветку, из которой сделаешь ПР, а этот ПР закроем. 
Дальше все ПРы будут у тебя из отдельных веток.

2023-03-06 10:16 UTC, dzencot commented on pages/_app.jsx
> +  const canonicalUrl = (BASE_URL + (router.asPath === '/' ? '' : router.asPath)).split('?')[0];
Для работы с урл можно использовать объект URL

2023-03-06 10:31 UTC, dzencot requested changes

2023-03-06 10:31 UTC, dzencot commented on components/Breadcrumb/index.jsx
> +  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000';
Предлагаю перенести переменную в этот конфиг https://github.com/Hexlet/hexlet-comparator/blob/main/next.config.js. Добавить сюда 
`basePath: process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000',`
После этого в роутере должен установиться корректный router.basePath

2023-03-06 10:37 UTC, fey commented
Я бы убрал, оставил только `.env.example` с примером переменных, которые нужно будет использовать.

2023-03-06 10:42 UTC, dzencot commented
Тогда давай добавим переменные окружения, а файл удалим. Где нужно их добавить?

2023-03-06 10:58 UTC, fey commented
на хероку

2023-03-07 01:51 UTC, EvSedov commented
@fey Итого:
1. Данный PR будет закрыт.
2. Я сделаю новый PR из ветки, чтобы в него не попали коммиты для хлебных крошек.
3. В `next.config.js` я ничего не добавляю, а переменную `BASE_URL` из `.env.production` я удаляю, она будет добавлена на хероку.
Все верно?

2023-03-07 06:16 UTC, dzencot commented
А почему не хочешь добавить в `next.config.js`? Мне кажется это лучшим решением, так как роутер сконфигурируется некстом

2023-03-07 06:31 UTC, EvSedov commented
> А почему не хочешь добавить в next.config.js? Мне кажется это лучшим решением, так как роутер сконфигурируется некстом

@dzencot, я не не хочу, я уточнял в итоге к чему вы пришли в результате своего диалога =) сейчас добавлю.

2023-03-09 05:40 UTC, closed without merging